"""Shared report types for all departments.

Every department generates an Officer Report following the same structure:
    Officer Report → Recommendations → Details → History

These dataclasses are the canonical definitions for:
    - Finding (docs/domain/finding.yaml)
    - Recommendation (docs/domain/recommendation.yaml)
    - Report (docs/domain/report.yaml)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Finding:
    """A noteworthy observation generated by a department.

    Maps to docs/domain/finding.yaml.
    """

    title: str
    description: str
    severity: str  # GREEN, BLUE, YELLOW, ORANGE, RED


@dataclass
class Recommendation:
    """An actionable recommendation from a department officer.

    Maps to docs/domain/recommendation.yaml.
    """

    priority: str  # low, medium, high, critical
    message: str
    reason: str
    action: str


@dataclass
class DepartmentReport:
    """Officer Report generated by a department.

    Maps to docs/domain/report.yaml.
    Every department produces this exact structure.
    """

    department: str = ""
    title: str = ""
    status: str = "BLUE"
    summary: str = ""
    findings: list[Finding] = field(default_factory=list)
    recommendations: list[Recommendation] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)
    history: dict[str, Any] = field(default_factory=dict)
    generated: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize for API response."""
        return {
            "department": self.department,
            "title": self.title,
            "status": self.status,
            "summary": self.summary,
            "findings": [
                {
                    "title": f.title,
                    "description": f.description,
                    "severity": f.severity,
                }
                for f in self.findings
            ],
            "recommendations": [
                {
                    "priority": r.priority,
                    "message": r.message,
                    "reason": r.reason,
                    "action": r.action,
                }
                for r in self.recommendations
            ],
            "details": self.details,
            "history": self.history,
            "generated": self.generated,
        }
